version: '3.8'

services:
  api:
    build: .
    container_name: api_backend
    ports:
      - '3000:3000'
    volumes:
      - .env:/app/.env
    networks:
      - webnet
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    container_name: postgres_todo
    image: postgres:16.3
    restart: always
    command: postgres -c 'max_connections=500'
    volumes:
      - ./.persistence_store/postgres/db-data:/var/lib/postgresql/data
      - ./.persistence_store/postgres/db:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: developer
      POSTGRES_DBS: todo_db
      POSTGRES_EXTENSIONS: citext,uuid-ossp
    networks:
      - webnet
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U developer" ]
      interval: 5s
      timeout: 5s
      retries: 5

  postgres-init:
    image: postgres
    container_name: postgresql-init
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      PGPASSWORD: developer
    networks:
      - webnet
    command:
      - /bin/bash
      - -c
      - |
        psql -h postgres -U developer -tc "SELECT 1 FROM pg_database WHERE datname = 'todo_db'" | grep -q 1 | psql -h postgres -U developer -c "CREATE DATABASE todo_db"

networks:
  webnet:
    driver: bridge

